version: 2.1

executors:
  ci-executor:
    docker:
      - image: circleci/node:10.16.0-stretch-browsers

references:
  npm_cache_key: &npm_cache_key
    dependency-npm-{{ checksum "yarn.lock" }}
  save_node_modules: &save_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - node_modules
  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key

  util_build_cache_key: &util_build_cache_key
    pyramid-utilities-dist-{{ .Branch }}-{{ .Revision }}
  save_util_dist: &save_util_dist
    save_cache:
      key: *util_build_cache_key
      paths:
        - dist/utilities
  restore_util_dist: &restore_util_dist
    restore_cache:
      keys:
        - *util_build_cache_key

  fl_build_cache_key: &fl_build_cache_key
    pyramid-fullerene-dist-{{ .Branch }}-{{ .Revision }}
  save_fl_dist: &save_fl_dist
    save_cache:
      key: *fl_build_cache_key
      paths:
        - dist/fullerene
  restore_fl_dist: &restore_fl_dist
    restore_cache:
      keys:
        - *fl_build_cache_key

jobs:
  install-packages:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Install the packages"
      - *restore_node_modules
      - run: yarn install
      - *save_node_modules

  lint:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start lint"
      - *restore_node_modules
      - run: yarn lint

  stylelint:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start stylelint"
      - *restore_node_modules
      - run: yarn stylelint

  check-formatted:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Check whether or not codes were formatted"
      - *restore_node_modules
      - run: yarn prettier:check

  util-build:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start build of utilities"
      - *restore_node_modules
      - run: yarn util:build
      - *save_util_dist

  util-test:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start unit test of utilities"
      - *restore_node_modules
      - run: yarn util:test
      - store_artifacts:
          path: coverage

  fl-build:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start build of fullerene"
      - *restore_node_modules
      - *restore_util_dist
      - run: yarn fl:build
      - *save_fl_dist

  fl-test:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start unit test of fullerene"
      - *restore_node_modules
      - *restore_util_dist
      - run: yarn fl:test
      - store_artifacts:
          path: coverage

  canaria-build:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start build of canaria"
      - *restore_node_modules
      - *restore_util_dist
      - *restore_fl_dist
      - run: yarn canaria:prebuild
      - run: yarn canaria:build

  canaria-test:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start unit test of canaria"
      - *restore_node_modules
      - *restore_util_dist
      - *restore_fl_dist
      - run: yarn canaria:prebuild
      - run: yarn canaria:test
      - store_artifacts:
          path: coverage

  canaria-e2e:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start e2e test of canaria"
      - *restore_node_modules
      - *restore_util_dist
      - *restore_fl_dist
      - run: yarn canaria:prebuild
      - run: yarn canaria:e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - install-packages
      - lint:
          requires:
            - install-packages
      - stylelint:
          requires:
            - install-packages
      - check-formatted:
          requires:
            - install-packages
      - util-build:
          requires:
            - lint
            - stylelint
            - check-formatted
      - util-test:
          requires:
            - lint
            - stylelint
            - check-formatted
      - fl-build:
          requires:
            - util-build
            - util-test
      - fl-test:
          requires:
            - util-build
            - util-test
      - canaria-build:
          requires:
            - fl-build
            - fl-test
      - canaria-test:
          requires:
            - fl-build
            - fl-test
      - canaria-e2e:
          requires:
            - fl-build
            - fl-test
