version: 2.1

executors:
  ci-executor:
    docker:
      - image: circleci/node:10.16.0-stretch-browsers

references:
  npm_cache_key: &npm_cache_key
    dependency-npm-{{ checksum "yarn.lock" }}
  save_node_modules: &save_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - node_modules
  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key

jobs:
  install-packages:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Install the packages"
      - *restore_node_modules
      - run: yarn install
      - *save_node_modules

  lint:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start lint"
      - *restore_node_modules
      - run: yarn lint

  stylelint:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start stylelint"
      - *restore_node_modules
      - run: yarn stylelint

  check-formatted:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Check whether or not codes were formatted"
      - *restore_node_modules
      - run: yarn prettier:check

  fl-build:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start build of fullerene"
      - *restore_node_modules
      - run: yarn fl:build

  fl-test:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start unit test of fullerene "
      - *restore_node_modules
      - run: yarn fl:test
      - store_artifacts:
          path: coverage

  canaria-build:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start build of canaria"
      - *restore_node_modules
      - run: yarn canaria:prebuild
      - run: yarn canaria:build

  canaria-test:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start unit test of canaria"
      - *restore_node_modules
      - run: yarn canaria:prebuild
      - run: yarn canaria:test
      - store_artifacts:
          path: coverage

  canaria-e2e:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start e2e test of canaria"
      - *restore_node_modules
      - run: yarn canaria:prebuild
      - run: yarn canaria:e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - install-packages
      - lint:
          requires:
            - install-packages
      - stylelint:
          requires:
            - install-packages
      - check-formatted:
          requires:
            - install-packages
      - fl-build:
          requires:
            - lint
            - stylelint
            - check-formatted
      - fl-test:
          requires:
            - lint
            - stylelint
            - check-formatted
      - canaria-build:
          requires:
            - fl-build
            - fl-test
      - canaria-test:
          requires:
            - fl-build
            - fl-test
      - canaria-e2e:
          requires:
            - fl-build
            - fl-test
