version: 2.1

executors:
  ci-executor:
    docker:
      - image: circleci/node:10.16.0-stretch-browsers

references:
  npm_cache_key: &npm_cache_key
    dependency-npm-{{ checksum "yarn.lock" }}
  save_node_modules: &save_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - node_modules
  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key

jobs:
  install-packages:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Install the packages"
      - *restore_node_modules
      - run: yarn install
      - *save_node_modules

  lint:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start lint"
      - *restore_node_modules
      - run: yarn lint

  stylelint:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start stylelint"
      - *restore_node_modules
      - run: yarn stylelint

  check-formatted:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Check whether or not codes were formatted"
      - *restore_node_modules
      - run: yarn prettier:check

  build:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start build"
      - *restore_node_modules
      - run: yarn build

  test:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start unit test"
      - *restore_node_modules
      - run: yarn test --watch false
      - store_artifacts:
          path: coverage

  e2e:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start e2e test"
      - *restore_node_modules
      - run: yarn e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - install-packages
      - lint:
          requires:
            - install-packages
      - stylelint:
          requires:
            - install-packages
      - check-formatted:
          requires:
            - install-packages
      - build:
          requires:
            - lint
            - stylelint
            - check-formatted
      - test:
          requires:
            - lint
            - stylelint
            - check-formatted
      - e2e:
          requires:
            - lint
            - stylelint
            - check-formatted
