name: Node CI

on:
  push:
    branches:
    - release/firebase

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy canaria app to Firebase
      run: |
        yarn
        yarn util:build
        yarn fl:build
        yarn canaria:prebuild
        yarn canaria:deploy
